/// Our command table.
///
/// Every entry is composed of the following fields:
///
/// name: a string representing the command name.
/// proc: pointer to the function implementing the command.
/// arity: number of arguments, it is possible to use -N to say >= N.
pub var table = [_]Command{
    .{ .name = "ping", .proc = Server.pingCommand, .arity = -1, .sflags = "tF" },
    .{ .name = "echo", .proc = Server.echoCommand, .arity = 2, .sflags = "F" },
    .{ .name = "auth", .proc = Server.authCommand, .arity = 2, .sflags = "sltMF" },
    .{ .name = "time", .proc = Server.timeCommand, .arity = 1, .sflags = "RF" },
    .{ .name = "object", .proc = Object.objectCommand, .arity = -2, .sflags = "rR" },
    .{ .name = "select", .proc = db.selectCommand, .arity = 2, .sflags = "lF" },
    .{ .name = "exists", .proc = db.existsCommand, .arity = -2, .sflags = "rF" },
    .{ .name = "del", .proc = db.delCommand, .arity = -2, .sflags = "w" },
    .{ .name = "unlink", .proc = db.unlinkCommand, .arity = -2, .sflags = "wF" },
    .{ .name = "rename", .proc = db.renameCommand, .arity = 3, .sflags = "w" },
    .{ .name = "renamenx", .proc = db.renamenxCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "dbsize", .proc = db.dbsizeCommand, .arity = 1, .sflags = "rF" },
    .{ .name = "randomkey", .proc = db.randomkeyCommand, .arity = 1, .sflags = "rR" },
    .{ .name = "move", .proc = db.moveCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "scan", .proc = db.scanCommand, .arity = -2, .sflags = "rR" },
    .{ .name = "ttl", .proc = expire.ttlCommand, .arity = 2, .sflags = "rFR" },
    .{ .name = "pttl", .proc = expire.pttlCommand, .arity = 2, .sflags = "rFR" },
    .{ .name = "persist", .proc = expire.persistCommand, .arity = 2, .sflags = "wF" },
    .{ .name = "touch", .proc = expire.touchCommand, .arity = -2, .sflags = "rF" },
    .{ .name = "expire", .proc = expire.expireCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "expireat", .proc = expire.expireatCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "pexpire", .proc = expire.pexpireCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "pexpireat", .proc = expire.pexpireatCommand, .arity = 3, .sflags = "wF" },
    .{ .name = "set", .proc = string.setCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "setnx", .proc = string.setnxCommand, .arity = 3, .sflags = "wmF" },
    .{ .name = "setex", .proc = string.setexCommand, .arity = 4, .sflags = "wm" },
    .{ .name = "psetex", .proc = string.psetexCommand, .arity = 4, .sflags = "wm" },
    .{ .name = "mset", .proc = string.msetCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "msetnx", .proc = string.msetnxCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "get", .proc = string.getCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "mget", .proc = string.mgetCommand, .arity = -2, .sflags = "rF" },
    .{ .name = "getset", .proc = string.getsetCommand, .arity = 3, .sflags = "wm" },
    .{ .name = "incr", .proc = string.incrCommand, .arity = 2, .sflags = "wmF" },
    .{ .name = "decr", .proc = string.decrCommand, .arity = 2, .sflags = "wmF" },
    .{ .name = "incrby", .proc = string.incrbyCommand, .arity = 3, .sflags = "wmF" },
    .{ .name = "decrby", .proc = string.decrbyCommand, .arity = 3, .sflags = "wmF" },
    .{ .name = "incrbyfloat", .proc = string.incrbyfloatCommand, .arity = 3, .sflags = "wmF" },
    .{ .name = "strlen", .proc = string.strlenCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "append", .proc = string.appendCommand, .arity = 3, .sflags = "wm" },
    .{ .name = "setrange", .proc = string.setrangeCommand, .arity = 4, .sflags = "wm" },
    .{ .name = "getrange", .proc = string.getrangeCommand, .arity = 4, .sflags = "r" },
    .{ .name = "lpush", .proc = list.lpushCommand, .arity = -3, .sflags = "wmF" },
    .{ .name = "rpush", .proc = list.rpushCommand, .arity = -3, .sflags = "wmF" },
    .{ .name = "lpushx", .proc = list.lpushxCommand, .arity = -3, .sflags = "wmF" },
    .{ .name = "rpushx", .proc = list.rpushxCommand, .arity = -3, .sflags = "wmF" },
    .{ .name = "lpop", .proc = list.lpopCommand, .arity = 2, .sflags = "wF" },
    .{ .name = "rpop", .proc = list.rpopCommand, .arity = 2, .sflags = "wF" },
    .{ .name = "rpoplpush", .proc = list.rpoplpushCommand, .arity = 3, .sflags = "wm" },
    .{ .name = "blpop", .proc = list.blpopCommand, .arity = -3, .sflags = "ws" },
    .{ .name = "brpop", .proc = list.brpopCommand, .arity = -3, .sflags = "ws" },
    .{ .name = "brpoplpush", .proc = list.brpoplpushCommand, .arity = 4, .sflags = "wms" },
    .{ .name = "linsert", .proc = list.linsertCommand, .arity = 5, .sflags = "wm" },
    .{ .name = "lindex", .proc = list.lindexCommand, .arity = 3, .sflags = "r" },
    .{ .name = "lset", .proc = list.lsetCommand, .arity = 4, .sflags = "wm" },
    .{ .name = "llen", .proc = list.llenCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "lrange", .proc = list.lrangeCommand, .arity = 4, .sflags = "r" },
    .{ .name = "ltrim", .proc = list.ltrimCommand, .arity = 4, .sflags = "w" },
    .{ .name = "lrem", .proc = list.lremCommand, .arity = 4, .sflags = "w" },
    .{ .name = "hset", .proc = hash.hsetCommand, .arity = -4, .sflags = "wmF" },
    .{ .name = "hmset", .proc = hash.hsetCommand, .arity = -4, .sflags = "wmF" },
    .{ .name = "hincrby", .proc = hash.hincrbyCommand, .arity = 4, .sflags = "wmF" },
    .{ .name = "hincrbyfloat", .proc = hash.hincrbyfloatCommand, .arity = 4, .sflags = "wmF" },
    .{ .name = "hsetnx", .proc = hash.hsetnxCommand, .arity = 4, .sflags = "wmF" },
    .{ .name = "hget", .proc = hash.hgetCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "hmget", .proc = hash.hmgetCommand, .arity = -3, .sflags = "rF" },
    .{ .name = "hdel", .proc = hash.hdelCommand, .arity = -3, .sflags = "wF" },
    .{ .name = "hlen", .proc = hash.hlenCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "hstrlen", .proc = hash.hstrlenCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "hscan", .proc = hash.hscanCommand, .arity = -3, .sflags = "rR" },
    .{ .name = "hexists", .proc = hash.hexistsCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "hkeys", .proc = hash.hkeysCommand, .arity = 2, .sflags = "rS" },
    .{ .name = "hvals", .proc = hash.hvalsCommand, .arity = 2, .sflags = "rS" },
    .{ .name = "hgetall", .proc = hash.hgetallCommand, .arity = 2, .sflags = "rR" },
    .{ .name = "sadd", .proc = set.saddCommand, .arity = -3, .sflags = "wmF" },
    .{ .name = "sscan", .proc = set.sscanCommand, .arity = -3, .sflags = "rR" },
    .{ .name = "srem", .proc = set.sremCommand, .arity = -3, .sflags = "wF" },
    .{ .name = "sismember", .proc = set.sismemberCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "scard", .proc = set.scardCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "smove", .proc = set.smoveCommand, .arity = 4, .sflags = "wF" },
    .{ .name = "sunion", .proc = set.sunionCommand, .arity = -2, .sflags = "rS" },
    .{ .name = "sunionstore", .proc = set.sunionstoreCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "sdiff", .proc = set.sdiffCommand, .arity = -2, .sflags = "rS" },
    .{ .name = "sdiffstore", .proc = set.sdiffstoreCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "sinter", .proc = set.sinterCommand, .arity = -2, .sflags = "rS" },
    .{ .name = "smembers", .proc = set.sinterCommand, .arity = 2, .sflags = "rS" },
    .{ .name = "sinterstore", .proc = set.sinterstoreCommand, .arity = -3, .sflags = "wm" },
    .{ .name = "spop", .proc = set.spopCommand, .arity = -2, .sflags = "wRF" },
    .{ .name = "srandmember", .proc = set.srandmemberCommand, .arity = -2, .sflags = "rR" },
    .{ .name = "zadd", .proc = zset.zaddCommand, .arity = -4, .sflags = "wmF" },
    .{ .name = "zincrby", .proc = zset.zincrbyCommand, .arity = 4, .sflags = "wmF" },
    .{ .name = "zcard", .proc = zset.zcardCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "zscore", .proc = zset.zscoreCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "zrank", .proc = zset.zrankCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "zrevrank", .proc = zset.zrevrankCommand, .arity = 3, .sflags = "rF" },
    .{ .name = "zrem", .proc = zset.zremCommand, .arity = -3, .sflags = "wF" },
    .{ .name = "zrange", .proc = zset.zrangeCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zrevrange", .proc = zset.zrevrangeCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zrangebyscore", .proc = zset.zrangebyscoreCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zrevrangebyscore", .proc = zset.zrevrangebyscoreCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zremrangebyrank", .proc = zset.zremrangebyrankCommand, .arity = 4, .sflags = "w" },
    .{ .name = "zremrangebyscore", .proc = zset.zremrangebyscoreCommand, .arity = 4, .sflags = "w" },
    .{ .name = "zremrangebylex", .proc = zset.zremrangebylexCommand, .arity = 4, .sflags = "w" },
    .{ .name = "zrangebylex", .proc = zset.zrangebylexCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zrevrangebylex", .proc = zset.zrevrangebylexCommand, .arity = -4, .sflags = "r" },
    .{ .name = "zcount", .proc = zset.zcountCommand, .arity = 4, .sflags = "rF" },
    .{ .name = "zlexcount", .proc = zset.zlexcountCommand, .arity = 4, .sflags = "rF" },
    .{ .name = "zscan", .proc = zset.zscanCommand, .arity = -3, .sflags = "rR" },
    .{ .name = "zpopmin", .proc = zset.zpopminCommand, .arity = -2, .sflags = "wF" },
    .{ .name = "zpopmax", .proc = zset.zpopmaxCommand, .arity = -2, .sflags = "wF" },
    .{ .name = "bzpopmin", .proc = zset.bzpopminCommand, .arity = -3, .sflags = "wsF" },
    .{ .name = "bzpopmax", .proc = zset.bzpopmaxCommand, .arity = -3, .sflags = "wsF" },
    .{ .name = "zunionstore", .proc = zset.zunionstoreCommand, .arity = -4, .sflags = "wm" },
    .{ .name = "zinterstore", .proc = zset.zinterstoreCommand, .arity = -4, .sflags = "wm" },
    .{ .name = "xadd", .proc = stream.xaddCommand, .arity = -5, .sflags = "wmFR" },
    .{ .name = "xdel", .proc = stream.xdelCommand, .arity = -3, .sflags = "wF" },
    .{ .name = "xlen", .proc = stream.xlenCommand, .arity = 2, .sflags = "rF" },
    .{ .name = "xrange", .proc = stream.xrangeCommand, .arity = -4, .sflags = "r" },
    .{ .name = "xrevrange", .proc = stream.xrevrangeCommand, .arity = -4, .sflags = "r" },
    .{ .name = "xtrim", .proc = stream.xtrimCommand, .arity = -2, .sflags = "wFR" },
    .{ .name = "xread", .proc = stream.xreadCommand, .arity = -4, .sflags = "rs" },
    .{ .name = "xreadgroup", .proc = stream.xreadCommand, .arity = -7, .sflags = "ws" },
    .{ .name = "xgroup", .proc = stream.xgroupCommand, .arity = -2, .sflags = "wm" },
    .{ .name = "xack", .proc = stream.xackCommand, .arity = -4, .sflags = "wF" },
    .{ .name = "xpending", .proc = stream.xpendingCommand, .arity = -3, .sflags = "rR" },
    .{ .name = "xclaim", .proc = stream.xclaimCommand, .arity = -6, .sflags = "wRF" },
    .{ .name = "xsetid", .proc = stream.xsetidCommand, .arity = 3, .sflags = "wmF" },
    .{ .name = "xinfo", .proc = stream.xinfoCommand, .arity = -2, .sflags = "rR" },
    .{ .name = "subscribe", .proc = pubsub.subscribeCommand, .arity = -2, .sflags = "pslt" },
    .{ .name = "psubscribe", .proc = pubsub.psubscribeCommand, .arity = -2, .sflags = "pslt" },
    .{ .name = "unsubscribe", .proc = pubsub.unsubscribeCommand, .arity = -1, .sflags = "pslt" },
    .{ .name = "punsubscribe", .proc = pubsub.punsubscribeCommand, .arity = -1, .sflags = "pslt" },
    .{ .name = "pubsub", .proc = pubsub.pubsubCommand, .arity = -2, .sflags = "pltR" },
    .{ .name = "publish", .proc = pubsub.publishCommand, .arity = 3, .sflags = "pltF" },
    .{ .name = "watch", .proc = multi.watchCommand, .arity = -2, .sflags = "sF" },
    .{ .name = "unwatch", .proc = multi.unwatchCommand, .arity = 1, .sflags = "sF" },
    .{ .name = "multi", .proc = multi.multiCommand, .arity = 1, .sflags = "sF" },
    .{ .name = "discard", .proc = multi.discardCommand, .arity = 1, .sflags = "sF" },
    .{ .name = "exec", .proc = multi.execCommand, .arity = 1, .sflags = "sM" },
    .{ .name = "eval", .proc = scritping.evalCommand, .arity = -3, .sflags = "s" },
    .{ .name = "evalsha", .proc = scritping.evalShaCommand, .arity = -3, .sflags = "s" },
    .{ .name = "script", .proc = scritping.scriptCommand, .arity = -2, .sflags = "s" },
    .{ .name = "save", .proc = rdb.saveCommand, .arity = 1, .sflags = "as" },
    .{ .name = "bgsave", .proc = rdb.bgsaveCommand, .arity = -1, .sflags = "as" },
};

pub const Command = struct {
    pub const Proc = *const fn (cli: *Client) void;

    name: []const u8,
    proc: Proc,
    arity: i32,
    /// Flags as string representation, one char per flag.
    sflags: []const u8,
    /// he actual flags, obtained from the 'sflags' field.
    flags: i32 = 0,
};

const Client = @import("networking.zig").Client;
const string = @import("t_string.zig");
const list = @import("t_list.zig");
const hash = @import("t_hash.zig");
const set = @import("t_set.zig");
const zset = @import("t_zset.zig");
const stream = @import("t_stream.zig");
const db = @import("db.zig");
const expire = @import("expire.zig");
const Server = @import("Server.zig");
const Object = @import("Object.zig");
const pubsub = @import("pubsub.zig");
const multi = @import("multi.zig");
const scritping = @import("scripting.zig");
const rdb = @import("rdb.zig");
